version: "3.8"
services:
  childdb:
    image: mongo
  childparentsdb:
    image: mongo
  childsiblingsdb:
    image: mongo
  genderdb:
    image: mongo
  questiondb: 
    image: mongo
  questionanswerdb:
    image: mongo
  questiontitledb:
    image: mongo    
  educationstatusdb:
    image: mongo
  childmaterializedviewdb:
    image: mcr.microsoft.com/mssql/server:2022-latest  
  rabbitmq:
    image: rabbitmq:3-management
  child.api:
    image: ${DOCKER_REGISTRY-}childapi
    build: 
      context: .
      dockerfile: src/projects/Child/Child.WebAPI/Dockerfile
  childmaterializedview.api:
    image: childmaterializedview_api_image
    build: 
      context: .
      dockerfile: src/projects/ChildMaterializedView/WebAPI/Dockerfile
  gender.api:
    image: gender_api_image
    build:
      context: .
      dockerfile: src/projects/Gender/Gender.WebAPI/Dockerfile    
volumes:
  childdb_volume:
  childparentsdb_volume:  
  childsiblingsdb_volume:
  genderdb_volume:
  questiondb_volume:
  questionanswerdb_volume:
  questiontitledb_volume:
  educationstatusdb_volume:
  childmaterializedview_volume:  
